### PR TITLE
use of eval considered harmful, frightening

### PR DESCRIPTION
**Pull request by jamestwebber**
I think this could be cleaned up further if desired but I had such a strong reaction to seeing `eval` that I had to write this immediately 😛

### CODE REVIEW

**Comment by HugoCornu** [comment]
perhaps you should explain why `eval` is problematic for you

**Comment by jamestwebber** [comment]
The title was tongue-in-cheek (I had just been chatting with @sjfleming), but generally-speaking `eval` should be avoided unless it's really necessary.

The main reason I think it should be removed is just because it makes the code hard to navigate. None of the `get_matrix_from_{}` functions were being called directly, which made their usage hard to identify and the code-path difficult to trace. So removing `eval` here would improve quality-of-life for developers and contributors.

There are a couple other reasons that are less immediately important but generally apply:

 - It prevents automated code-generation tools from optimizing over this path
 - It's just generally a bit slower than running code directly
 - It can run arbitrary code on the user's computer. This isn't a huge concern right now, but it does mean that changes to the loading code have to be monitored to make sure it's safe. e.g. with this design, it would be dangerous to let the user or a third-party extension add their own loading functions.

**Comment by HugoCornu** [comment]
Ok

To avoid changing the signature of `detect_input_data_type` and `class FileLoader`
and make `self.load_fn` a callable for your static code analysis tools
You could do something like that : 

```
from typing import Callable

FILE_EXT_MAPPING = {
    '' : {'data_type': 'cellranger_mtx', 'loader': get_matrix_from_cellranger_mtx},
    '.h5' : {'data_type': 'cellranger_h5', 'loader': get_matrix_from_cellranger_h5},
    '.txt' : {'data_type': 'dropseq_dge', 'loader': get_matrix_from_dropseq_dge},
    ...
}

def detect_input_data_type(input_file: str) -> str:
 
    file_no_gz = input_file[:-3] if input_file.endswith('.gz') else input_file
    file_ext = os.path.splitext())[1]

    try : 
          return EXT_MAPPING[file_ext]['data_type']
     except KeyError: 
          raise ValueError('Failed to determine input file typ...')

class FileLoader:
    """Make explicit guarantees about what a file-loading method yields."""

    def __init__(self, data_type):
        self.data_type = data_type
        self.load_fn:Callable =  {v['data_type']:v['loader'] for v in FILE_EXT_MAPPING.values()}[data_type]
```

**Comment by jamestwebber** [comment]
Why is it important to keep the signatures stable? This is a dev branch for a new version, and this code is not used elsewhere. It's all internal to `remove_background`

If it _is_ necessary to keep the signatures as-is, I would leave `detect_input_data_type` unchanged from before and make a global `data_type` -> `loader` dictionary, so `FileLoader` looks like this:

```
class FileLoader:
    """Make explicit guarantees about what a file-loading method yields."""

    def __init__(self, data_type):
        self.data_type = data_type
        self.load_fn = FILE_TYPE_MAPPING[data_type]
```

I don't see the value in the additional layer of indirection with mapping from the extension, and then iterating over the dictionary every time a file is loaded.

I had considered that version but then realized it was even simpler to just return the function directly, as `data_type` is not used again.

Honestly I'm not totally sure why `FileLoader` exists either, but that's a question for another PR.

**Comment by sjfleming** [comment]
Haha @jamestwebber , I appreciate the addition.  Also appreciate the input @HugoCornu .  I'm going to merge.

**Review by sjfleming — APPROVED** [review]

**Pull request merged**
