### PR TITLE
Update README.rst for new WDL

### LINKED ISSUE #27: Make a v0.1 Docker image + update Terra workflow

### PR DESCRIPTION
**Pull request by sjfleming**
New Terra WDL workflow.  Changed readme to specify python 3.7.

Closes #27

### CODE REVIEW

**Comment by mbabadi** [comment]
@sjfleming can you put the .wdl file under `GITHUB_ROOT/wdl/remove_background`?

**Comment by sjfleming** [comment]
The WDL is now located at 
`GITHUB_ROOT/wdl/cellbender_remove_background.wdl`

**Comment by sjfleming** [comment]
I have completed my documentation updates for now.

**Comment by mbabadi** [comment]
@sjfleming fantastic job on the additional documentation. everything looks good! :)

**Pull request merged**
