### PR TITLE
Add command-line options to address running out of GPU memory in posterior generation

### PR DESCRIPTION
**Pull request by alecw**
See #67 

Added options --posterior-batch-size and --cells-posterior-reg-calc.

Note that I removed version specifier for cudatoolkit because otherwise there were conflicts with other packages.  I don't know if that was the right thing to do.

### CODE REVIEW

**Comment by sjfleming** [comment]
Thanks @alecw !  I will merge this, and I might have to play around with the Dockerfile a bit.  It's been a while since I updated it, but I am also noticing that that version of cudatoolkit is now pretty old.  I just have to make sure that whatever version goes there ends up being compatible with the drivers from the base image, which will take a little bit of tinkering.  But yeah, cudatoolkit 9.2 is now so old that the version of pytorch required by the latest version of pyro is now incompatible with 9.2.

**Comment by alecw** [comment]
FWIW, the version of cudatoolkit in the docker image I built is 10.2.89

**Comment by sjfleming** [comment]
Huh, okay, I am surprised that is compatible with the base image
```nvcr.io/nvidia/cuda:9.2-base-ubuntu16.04```

**Comment by hemantgujar** [comment]
Hi 
I came across similar problem. But when I reduce --posterior-batch-size cellbender gives error. 

`--cuda `

> error at cellbender:remove-background: Preparing to write outputs to file... 
> RuntimeError: CUDA out of memory. Tried to allocate 5.12 GiB

`--cuda --posterior-batch-size 10` 

> got error at cellbender:remove-background: [epoch 090]  
> RuntimeError: CUDA out of memory. Tried to allocate 872.00 MiB

`--cuda --posterior-batch-size 10 --cells-posterior-reg-calc 50`

> got error at cellbender:remove-background: Running inference... 
> RuntimeError: CUDA out of memory. Tried to allocate 1.37 GiB

**Pull request merged**
